// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBotr6d5UIWZVddasx1_zq9I5maJBTAb7A',
    appId: '1:388664122102:web:1343b54ab5aeb4c3edead7',
    messagingSenderId: '388664122102',
    projectId: 'freerave-23-12-21',
    authDomain: 'freerave-23-12-21.firebaseapp.com',
    storageBucket: 'freerave-23-12-21.appspot.com',
    measurementId: 'G-QKPPTWFS24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADX23yb6ZWcnBt4sRcbOh1sDOcwrrBo_0',
    appId: '1:388664122102:android:625cc40f670bdb76edead7',
    messagingSenderId: '388664122102',
    projectId: 'freerave-23-12-21',
    storageBucket: 'freerave-23-12-21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh2gneaPFsV_kv2RTmX4Yjys0Fl3h-Awc',
    appId: '1:388664122102:ios:c1e89e66f51e900bedead7',
    messagingSenderId: '388664122102',
    projectId: 'freerave-23-12-21',
    storageBucket: 'freerave-23-12-21.appspot.com',
    iosBundleId: 'com.example.clickCounter',
  );
}
